spring:
  application:
    name: registry-server

server:
    port: ${PORT:8088}
      
security:
  user:
    name: ${EUREKA_USERNAME:user}
    password: ${EUREKA_PASSWORD:s3cr3t}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0    
     
logging:
  level:
     org:
       springframework:
         security: DEBUG  
