spring:
  cache:
    jcache:
      config: ehcache.xml
    
server:
  error:
    whitelabel:
      enabled: false
      
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
        defaultZone: http://localhost:8088/eureka/

logging:
  level:
     org:
       springframework:
         security: DEBUG      
