logging:
  level:
     org:
       springframework:
         security: DEBUG

server:
  error:
    whitelabel:
      enabled: true

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_SERVER_URL:http://localhost:8088}/eureka/

security:
  user:
    name: ${APP_USERNAME:user}
    password: ${APP_PASSWORD:s3cr3t}

#---
#spring:
#  profiles: heroku

#eureka:
#  instance:
#    hostname: ${EUREKA_DOMAIN_NAME} 
#    nonSecurePort: 80
#  password: ${EUREKA_USER_PASSWORD:password}  

