logging:
  path: /logs/
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n" 
  level:
    root: WARN
    org.springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

server:
  error:
    whitelabel:
      enabled: true

eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_SERVER_URL:http://localhost:8088}/eureka/

#security:
#  user:
#    name: ${EUREKA_USERNAME}
#    password: ${EUREKA_PASSWORD}

---
spring:
  profiles: heroku

eureka:
  instance:
    hostname: ${EUREKA_DOMAIN_NAME} 
    nonSecurePort: 80
  password: ${EUREKA_USER_PASSWORD:password}  

