version: '3'

services:
  nextgen-config:
    build: configuration
    ports:
      - 8199:8199
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
  
  nextgen-registry:
    build: service-registry
    ports:
      - 8088:8088
    depends_on:
      - "nextgen-config"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      
  nextgen-profile:
    build: profile
    ports:
      - 8001:8001
    depends_on:
      - "nextgen-config"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      
  nextgen-reservation:
    build: reservation
    ports:
      - 8002:8002
    depends_on:
      - "nextgen-config"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      
  nextgen-addon-svcs:
    build: addons-services
    ports:
      - 8003:8003
    depends_on:
      - "nextgen-config"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      
  nextgen-gateway:
    build: gateway
    ports:
      - 8080:8080
    depends_on:
      - "nextgen-config"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      
  nextgen-monitor:
    build: monitoring
    ports:
      - 9080:9080
    depends_on:
      - "nextgen-config"
      - "nextgen-registry"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
 