version: '2.1'

services:
  nextgen-config:
    image: prithwish24/nextgen-config
    ports:
      - 8199:8199
    volumes:
      - spring-config-repo:/var/apps/config-repo
    networks:
      - spring-cloud-network
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      port: $port
  

  nextgen-registry:
    image: prithwish24/nextgen-registry
    ports:
      - 8088:8088
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port


  nextgen-profile:
    image: prithwish24/nextgen-profile
    ports:
      - 8001:8001
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
      - nextgen-registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port
      


  nextgen-reservation:
    image: prithwish24/nextgen-reservation
    ports:
      - 8002:8002
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
      - nextgen-registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port


  nextgen-addon-svcs:
    image: prithwish24/nextgen-addon-svcs
    ports:
      - 8003:8003
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
      - nextgen-registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port
      

  nextgen-gateway:
    image: prithwish24/nextgen-gateway
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
      - nextgen-registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port
      

  nextgen-monitor:
    image: prithwish24/monitoring
    ports:
      - 9080:9080
    networks:
      - spring-cloud-network
    links:
      - nextgen-config:nextgen-config
    depends_on:
      - nextgen-config
      - nextgen-registry
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NEXTGEN_REGISTRY_SERVER: $NEXTGEN_REGISTRY_SERVER
      port: $port


networks:
  spring-cloud-network:
    driver: bridge

volumes:
  spring-config-repo:
    external: true

