spring:
  application:
    name: nextgen-gateway
    
server:
  port: 8199

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
        defaultZone: http://localhost:8198/eureka/
 
  
logging:
  level:
     org:
       springframework:
         security: DEBUG  