spring:
  cache:
    jcache:
      config: ehcache.xml

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
        defaultZone: http://nextgen-registry:8088/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
