logging:
  level:
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled: true

      
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
 
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current
#
#spring:
#  rabbitmq:
#    host: rabbitmq
