#spring:
#  application:
#    name: reservation-service
    
#server:
#  port: ${port:8002}
#  error:
#   whitelabel:
#      enabled: false

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: false
#    serviceUrl:
#        defaultZone: http://nextgen-registry:8088/eureka/
          
#logging:
#  level:
#     org:
#       springframework:
#         security: DEBUG  
