eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: true
    secure-port: 10234
    non-secure-port: 8088
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 
spring:
  datasource:
    url: jdbc:h2:mem:dbname
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create