spring:
  application:
    name: config-server
  profiles:
    active: native

server:
  port: ${port:8199}  
      
management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

security:
  user:
    name: root
    password: ${CONFIG_SERVICE_PASSWORD:s3cr3t}
    
eureka:
  instance:
    hostname: ${NEXTGEN_REGISTRY_SERVER:localhost}
  client:
    serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:8088/eureka/

        
---
spring:  
  cloud:
    config:
      profile: native
      server:
        bootstrap: true
        native:
          search-locations: classpath:/shared

---
spring:
  cloud:
    config:
      profile: github
      server:
        bootstrap: false
        git:
          uri: https://github.com/prithwish24/nextgen-services-cloud-config.git
#          uri: file:///d:/git-local-repo
#          username: prithwish24
#          password: ####
          timeout: 15
          clone-on-start: true
