server:
  port: ${port:8199}  
      
management:
  security:
    enabled: false

endpoints:
  health:
    sensitive: false

security:
  user:
    name: root
    password: ${CONFIG_SERVICE_PASSWORD}